#!/usr/bin/env bash
# Tells a story based on /etc/passwd entries
while IFS=: read -r u p uid g i h s; do echo "The user $u is part of the $g gang, lives in $h and rides $s. $uid's place is protected by the passcode $p, more info about the user here: $i"; done < /etc/passwd
