#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code
awk '$9 ~ /^[0-9]+$/ {c[$1" "$9]++} END {n=asorti(c,k,"@val_num_desc"); for(i=1;i<=n;i++) printf "%5d %s\n", c[k[i]], k[i]}' apache-access.log
