#!/usr/bin/env bash
# Prints "To infinity and beyond" indefinitely; reacts to SIGTERM with "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
